### ISSUE TITLE
IPLD Tutorial #1

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#107]
## Problem Description
Redo ipld walkthrough tutorial video by @walkerlj0 & @rvagg found here https://www.youtube.com/watch?v=nLgxTYoF-K4

### Purpose
 This will be a helpful resource to do a hands-on IPLD DAG structures.

### Proposed Solution
- [x] Split up the video into parts (target is 4-5 parts, but not essential)
- [x] Short write ups of commands used for the reader to follow part by part
- [ ] Highlight command line and any actions taken to draw visual attention 
- [x] Exported to 1080p 

The parts will be to go through short walk throughs of different sections of the video. Will include links to resources used in each, pages visited, dependencies (e.g. IPFS desktop, ipfs-go) and commands used. Suggested parts include: pre-req packages, DAGs, Roots, and UnixFS.

**Additional context**
Tutorial walkthrough used in the video is located at this [notion page](https://www.notion.so/pl-strflt/Explaining-DAGs-Roots-and-UnixFS-to-newbies-ff89ed883f1b4c5da8af13cd8ad07de9)
Additional resources include the learning material in the [current curriculum](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld) 

## Milestones
**1) Shorten video** 
This 1st milestone will be to edit out any bloopers, whitespace, unnecessary talking points and whatever else not directly contributing to the tutorial.

**2) Split into parts**
This goal will be to chop video up into rough parts and focus more on editing video to focus on each mission.

**3) Write ups**
After each part has been determined, we can proceed to write up "micro-articles" on what goes on in each video.

## Acceptance Criteria
Either a new subsection (lesson) in the curriculum or dedicated "Tutorial" page for the walk through. In the page there will be x parts with each micro-article underneath it, going over highlevel overviews of each video topic.

**Comment by walkerlj0** [comment]
Currently the video lives here: https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld

TBD create a set of short videos on each concept, then create a new section in IPLD for the tutorials, including a summary of each section

**Comment by mrodriguez3313** [comment]
@walkerlj0 Part "1" of new IPLD video series: https://drive.google.com/file/d/1an8Bztop9D1WkWuf69q6Fh_deyR21Vyl/view?usp=sharing

**Comment by walkerlj0** [comment]
@MarcoPolo where can I find the videos and GDoc? I lost it :o

**Comment by walkerlj0** [comment]
Draft/ written script & tutorial: https://docs.google.com/document/d/1sJrvfzQYNQ3zicu4kTP8Hl4cgVtKqYG1T4W93CbhkSA/edit#

**Comment by walkerlj0** [comment]
Due date for Part 1 video: Fri Jan 20 (Review Jan 24)

Due date for Part 2 video: Fri Feb 3 (Review  Feb 7)

Due date for Part 3 video: Fri Feb 17 (Review Feb 21)

**Comment by mrodriguez3313** [comment]
For video 1:
* I still need add in sectional banners for each new subject.
* Here is the latest camtasia file [on drive](https://drive.google.com/file/d/1EAd2V9Atf68xjY16wJUjWxvzetBUUqqA/view?usp=share_link)
* Writing the curriculum tutorial in this [google doc](https://docs.google.com/document/d/1sJrvfzQYNQ3zicu4kTP8Hl4cgVtKqYG1T4W93CbhkSA/edit?usp=sharing)

@walkerlj0

**Comment by walkerlj0** [comment]
TBD by Jan 24, review Script & watch video @walkerlj0

**Comment by walkerlj0** [comment]
@mrodriguez3313 per our convo Friday, you uploaded the wrong video (it was the template) could you upload the link to the right GDrive version of the video here?

**Comment by mrodriguez3313** [comment]
There is a PR here https://github.com/protocol/launchpad/pull/476
docs version of this is here [google doc](https://docs.google.com/document/d/1sJrvfzQYNQ3zicu4kTP8Hl4cgVtKqYG1T4W93CbhkSA/edit#heading=h.3oa4eld5zxox)

**Comment by walkerlj0** [comment]
v2 of the video is here: https://docs.google.com/spreadsheets/d/1uyN_5uL4y6EFQVV7UHpPtiMQ_WWx9nzC36MCtNyCPfY/edit#gid=1116783173&range=6:6

**Comment by walkerlj0** [comment]
@mrodriguez3313 looks like it is merged, but some of the titles need editing. 
Should be called IPLD Data Structures (all caps) 

Tutorial #1 should be IPLD Pathing

**Comment by kt-wawro** [comment]
Doing some curriculum maintenance. It looks like this has been resolved so I'm closing the issue.
