### ISSUE TITLE
Add/extended (Sub) Section for IPNS

### ISSUE THREAD

**Issue by mrodriguez3313** [protocol/launchpad#162]
### Purpose
To add more content about IPNS into the curriculum. This can either be its own section or add on to the current subsection that currently exists in ["Mutable Content"](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/mutable-content) 

### Proposed Solution

- [x] Graphics and a couple paragraphs about how IPNS works in more detail
   - [x] Graphics - fix "pinning options" image to portray a clearer & more relevant message
   - [x] paragraphs
- [x] Short explanation of tradeoffs and common shortfalls
- [x] Show/describe how publish/subcribe (pubsub) works along with it and compliments it 
- [x] Show/describe how IPNS works with DNS (aka DNSLink) and use ipfs.io as an example
- [x] Add content about the IPNS records themselves (nonce value, expiration time, IPNS object, etc...). 
- [x] ~~Short videos for how to operate IPNS from CLI~~

It would be cool to show what you can do with IPNS. We have already shown how to publish something with IPNS in ["The IPFS API (Tutorial)"](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/ipfs-api). But we can show how to enable pubsub with IPNS, we can show how to publish with a generated key that is not "self" (your default key on your ipfs node), export and import keys. All of this is best operated through the CLI, in my experience, so we can also do a short video going through this process and it will be easy to follow. These videos can be similar to ones done in ["IPFS Setup (Tutorial)"](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/setup#ipfs-basics-accessing-files) It can extend and compliment the content in [docs.ipfs.io/ipns](https://docs.ipfs.io/concepts/ipns/#interplanetary-name-system-ipns). It would be a big rabbit hole if we go too much into the weeds of IPNS because of a variety of edge cases that have no easy solutions/explanations. So the trick will be to hint at those issues without addressing them too explicitly. This can farm engagement for deep dives.

**Where Can we find out more about this topic?**
Here are some resources that explain common points regarding IPNS: 

* Current ipns spec https://github.com/ipfs/specs/blob/main/IPNS.md
* overview of ipns https://pl-strflt.notion.site/IPNS-Overview-and-FAQ-071b9b14f12045ea842a7d51cfb47dff#0963fe6b470a4c55b1929146c360dc95
* https://github.com/ipfs/specs/blob/main/naming/pubsub.md
* https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipfs-pubsub
* https://discuss.ipfs.io/t/ipns-beyond-the-basics-no-ipns-pinning-service-any-docs-on-this/13424
* https://discuss.ipfs.io/t/ipns-use-cases-what-is-dragging-down-ipns/9817
* https://github.com/ipfs/specs/issues/268 (**Edit**: adding this resource)
* This issue talks a bit about IPRS (Which I still don't really know what that is), but it has good insights about issues in IPNS that are STILL relevant today. https://discuss.ipfs.io/t/confusion-about-ipns/1414

## Milestones
**1) Publish written learning material** (2 weeks; 1 for write ups + 1 week for possible time-delayed technical reviews)
   This includes material for IPNS, Pubsub+IPNS, and DNSLink. Both Deep and Shallow tracks.

**2) Video guides** (2 week, 1 week for research and recording + 1 week for editing and time-delayed reviews) 
   This includes CLI follow-alongs and, if feasible, programmable guides

**3) Merge into main from gitbook**
Due to curriculum website change, the final step is moving the merged content from gitbook -> mutable-content.md into main -> mutable-content.md

## Acceptance Criteria
Acceptable resolution of this issue would entail written teaching material for IPNS, DNSlink, & routing options and tradeoffs.

**Comment by mrodriguez3313** [comment]
Completed this issue with this final commit [d112a2428f695e915c0969524d8c0ccd6cd366da](https://github.com/protocol/launchpad/commit/d112a2428f695e915c0969524d8c0ccd6cd366da)
