### ISSUE TITLE
Create a 'Build an FVM Smart Contract' Tutorial

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#459]
## Problem Description
We need a tutorial to engage Launchpad residents that also includes how-to screencasts, and uses the Hyperspace Testnet (instead of Wallaby testnet with less availability)

### Purpose
Create an (updated) tutorial for FVM for Launchpad Residents that we can add videos & our format to

### Proposed Solution
We currently have the tutorial published on docs site, but it’s not particular to Filecoin
[Quickstart under docs.filecoin.io -> Developers -> Smart Contracts](https://docs.filecoin.io/developers/smart-contracts/quickstart/)
Used the Remix IDE with the Ethereum IDE: https://remix-ide.readthedocs.io/en/latest/

- [ ] Copy the [tutorial on filecoin docs]((https://docs.filecoin.io/developers/smart-contracts/quickstart/)) into a tutorial into Launchpad platfrom as-is. Make it 3 separate sections
- [ ] Update the first section to use Hyperspace testnet
- [ ] Create 3 videos for each section 
- [ ] Work with Zak A to create more sections to the tutorial

**Where Can we find out more about this topic?**
Matt Hamilton & Zak Ayesh

**Additional context**
See notes from meetings & resources: [https://docs.google.com/document/d/1KG_j-6Ud9wuuzbF6vNNi5sMsuvplpCwxpk8Gq2sF8A8/edit#](https://docs.google.com/document/d/1KG_j-6Ud9wuuzbF6vNNi5sMsuvplpCwxpk8Gq2sF8A8/edit#)

## Milestones (Optional)
**1) Copy Tutorial as-is** Text

**2) Update to use Hyperspace Testnet** Text

## Acceptance Criteria
There exists a tutorial using the Hyperspace testnet with 3 sections and a screencast video for each section

**Comment by walkerlj0** [comment]
MVP Created

**Comment by walkerlj0** [comment]
@enoldev set up a meeting with Sara T and/or Zak by next week
