### ISSUE TITLE
GitBook resync fixup tasks

### ISSUE THREAD

**Issue by rvagg** [protocol/launchpad#48]
Summary: GitBook stopped syncing the content, possibly due to unresolvable conflicts between editing on GitBook vs editing in this repo. I desynced GitBook, made an orphaned branch here, `gitbook`, and resynced to that and told it to push content to there. I then desynced again and reconnected it the other way around so now it's pulling from the `gitbook` branch. `gitbook` is now the default branch here that we can merge in to (we can fix that up later if it's too annoying but it works for now!).

The round-trip through GitBook made a lot of layout changes; I've fixed up the easier ones so now the `gitbook` branch and `main` branch are fairly similar, a `git diff` between them shows the big differences. The main differences now are:

* The custom GitBook config is gone and we're back to the default layout - SUMMARY.md in the root and .gitbook/assets in the root. `main` had docs/summary.md and docs/.gitbook/assets. We could try and tinker with this, but it's working for now.
* The topic/about.md pages are now all topic/README.md pages. Probably wouldn't be a problem to rename them but all links pointing to them would also need to be fixed. It's working for now.

Some things that need fixing that I've noticed so far:

* [x] twitter-banner-1500x500.png missing but it's referred to in a lot of places, we should either remove those or put in a file and fix the links to it #45
* [x] libp2p content has funky links, they all need checking. I've cleaned some but there are others that are missing and are not obvious to me. #46
* [x] IPLD content was copy-pasted from here to GitBook so the round-trip has changed all the formatting and it's very difficult to diff. I'll go through and harmonise the differences since that was my content originally.
* [x] PRs #31 and #42 will need to be redone but against the `gitbook` branch; I don't think they're going to be easy to salvage using Git trickery and may be easier to do some copying and pasting into a new branch with new PRs.

**Comment by walkerlj0** [comment]
Re-iteration-- I created an orphan branch with the ipfs content--- then manually copied over the /docs/ipfs content-- it's syncing just fine now!
